service: fintoc-integration

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  environment:
    FINTOC_API_KEY: ${env:FINTOC_API_KEY}

functions:
  createPaymentIntent:
    handler: src/presentation/api/create-payment-intent.handler
    events:
      - httpApi:
          path: /payment-intent
          method: post

plugins:
  - serverless-plugin-typescript
